[package]
name = "carve-sys"
version = "0.1.0"
authors = ["Ryan Huang"]
build = "build.rs"
edition = "2018"

[features]
default = ["opencl"]
opencl = []

[build-dependencies]
bindgen = "0.52"
cc = "1.0"
